#!/usr/bin/env php
<?php

/**
 * Handling console script execution
 */

use App\Loader;
use SensioLabs\Security\SecurityChecker;
use Symfony\Component\Console\Application;
use System\UI\Console\Command\ModuleBuilderCommand;
use SensioLabs\Security\Command\SecurityCheckerCommand;

require __DIR__.'/bootstrap/autoload.php';

$isConsole = true;

// bootstapping
$container = require_once __DIR__.'/bootstrap/app.php';

$application = new Application();
$application->add(new SecurityCheckerCommand(new SecurityChecker()));
$application->add(new ModuleBuilderCommand());

Loader::loadCommands($application, $container);

$application->run();
